- hosts: localhost
  tasks:
          - name: configuring docker yum repo
            yum_repositiory:
                    name: docker
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
                    
          - name: installing docker
            command: 'yum intall docker-ce  --nobest  -y'
            
          - name: starting docker services
            service: 
                    name: docker
                    state: started
                    
          - name: pulling docker image
            docker_image:
                    name: httpd
                    tag: latest 
                    
          - name: launching container
            docker_container:
                    name: "my_container"
                    image: httpd
                    state: started
                    expose:
                            "22"
                    published_ports:
                            "0.0.0.0:8080:80"
            register: docker

          - name: updating ansible inventory
            blockinfile:
                    block: |
                            [docker]
                            {{ docker.container.NetworkSettings.IPAddress }} ansible_ssh_user=root ansible_ssh_pass=accessforall  ansible_connection=ssh 
                            
                    dest: "/root/inven.txt"

       


       
