- hosts: docker 
  tasks:
          - name: install php
            package:
                    name: php
                    state: present

          - name: copying webpage
            template:
                    src: /root/task/index.php
                    dest: /usr/local/apache2/htdocs/

          - name: restarting httpd
            service:
                    name: httpd
                    state: restarted 



         
